name: ApiTest
main: com.minecats.cindyk.apitest.ApiTest
version: 2.0
authors: [cindy_k]
description: Lets test all Api things

commands:
  apitest:
    description: Test plugin via commands.
    aliases: api
